dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: jx-test1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: metadata-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: storefront-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
